### ISSUE TITLE
Criar algoritmo de pilha

### ISSUE THREAD

**Issue by cleiton-lima** [Att4ck3rS3cur1ty/Locadora-de-Automoveis#3]

**Comment by Att4ck3rS3cur1ty** [comment]
Algoritmo de quick sort adicionado: [adding quick sort algorithm to order by getQuilometragem
](https://github.com/Att4ck3rS3cur1ty/Locadora-de-Automoveis/commit/5edc317e2b750be0198ccb69b3fdaca70ea63bee)

**Comment by cleiton-lima** [comment]
Implementação concluída.
