### ISSUE TITLE
Criar algoritmo de fila

### ISSUE THREAD

**Issue by cleiton-lima** [Att4ck3rS3cur1ty/Locadora-de-Automoveis#4]

**Comment by Att4ck3rS3cur1ty** [comment]
Adicionada implementação para ordenar por ano. [adding bubble sort algorithm implementation to order Veiculos by getA…
](https://github.com/Att4ck3rS3cur1ty/Locadora-de-Automoveis/commit/3f69e372bc81c7500de7c8c899fae13d8bd8f1e1)

**Comment by cleiton-lima** [comment]
Implementação concluída.
